version: "3.9"

services:
  app:
    build: .
    container_name: go-api
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - ${ENV_FILE:-.env.dev}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ${ENV_FILE:-.env.dev}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
